# Generated by Django 4.2.7 on 2024-01-09 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0002_colorvariant_sizevariant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_desription',
            new_name='product_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color_variant',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size_variant',
        ),
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(upload_to='categories'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='ecommapp.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='ecommapp.product'),
        ),
        migrations.DeleteModel(
            name='ColorVariant',
        ),
        migrations.DeleteModel(
            name='SizeVariant',
        ),
    ]
