# Generated by Django 4.2.7 on 2023-12-28 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_email_profile_full_name_profile_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_email_verfied',
            new_name='is_email_verified',
        ),
    ]
